simple: FORCE
	python ../w.py simple.w
	fasm bin/simple.asm
	chmod +x bin/simple
	bin/simple

add: FORCE
	python ../w.py add.w
	fasm bin/add.asm
	chmod +x bin/add
	bin/add

sub: FORCE
	python ../w.py sub.w
	fasm bin/sub.asm
	chmod +x bin/sub
	bin/sub

multiply: FORCE
	python ../w.py multiply.w
	fasm bin/multiply.asm
	chmod +x bin/multiply
	bin/multiply

modulus: FORCE
	python ../w.py modulus.w
	fasm bin/modulus.asm
	chmod +x bin/modulus
	bin/modulus

not: FORCE
	python ../w.py not.w
	fasm bin/not.asm
	chmod +x bin/not
	bin/not

var: FORCE
	python ../w.py var.w
	fasm bin/var.asm
	chmod +x bin/var
	bin/var

var2: FORCE
	python ../w.py var2.w
	fasm bin/var2.asm
	chmod +x bin/var2
	bin/var2

call: FORCE
	python ../w.py call.w
	fasm bin/call.asm
	chmod +x bin/call
	bin/call

call2: FORCE
	python ../w.py call2.w
	fasm bin/call2.asm
	chmod +x bin/call2
	bin/call2

string: FORCE
	python ../w.py string.w
	fasm bin/string.asm
	chmod +x bin/string
	bin/string

hello: FORCE
	python ../w.py hello.w
	fasm bin/hello.asm
	chmod +x bin/hello
	bin/hello

if: FORCE
	python ../w.py if.w
	fasm bin/if.asm
	chmod +x bin/if
	bin/if

for: FORCE
	python ../w.py for.w
	fasm bin/for.asm
	chmod +x bin/for
	bin/for

for2: FORCE
	python ../w.py for2.w
	fasm bin/for2.asm
	chmod +x bin/for2
	bin/for2

for3: FORCE
	python ../w.py for3.w
	fasm bin/for3.asm
	chmod +x bin/for3
	bin/for3

while: FORCE
	python ../w.py while.w
	fasm bin/while.asm
	chmod +x bin/while
	bin/while

while2: FORCE
	python ../w.py while2.w
	fasm bin/while2.asm
	chmod +x bin/while2
	bin/while2

repeat: FORCE
	python ../w.py repeat.w
	fasm bin/repeat.asm
	chmod +x bin/repeat
	bin/repeat

assignment: FORCE
	python ../w.py assignment.w
	fasm bin/assignment.asm
	chmod +x bin/assignment
	bin/assignment

pointer: FORCE
	python ../w.py pointer.w
	fasm bin/pointer.asm
	chmod +x bin/pointer
	bin/pointer

pointer2: FORCE
	python ../w.py pointer2.w
	fasm bin/pointer2.asm
	chmod +x bin/pointer2
	bin/pointer2

array_definition: FORCE
	python ../w.py array_definition.w
	fasm bin/array_definition.asm
	chmod +x bin/array_definition
	bin/array_definition

array_definition2: FORCE
	python ../w.py array_definition2.w
	fasm bin/array_definition2.asm
	chmod +x bin/array_definition2
	bin/array_definition2

array: FORCE
	python ../w.py array.w
	fasm bin/array.asm
	chmod +x bin/array
	bin/array

char_array: FORCE
	python ../w.py char_array.w
	fasm bin/char_array.asm
	chmod +x bin/char_array
	bin/char_array

char_pointer: FORCE
	python ../w.py char_pointer.w
	fasm bin/char_pointer.asm
	chmod +x bin/char_pointer
	bin/char_pointer

all: simple add sub multiply modulus not var var2 call call2 string hello if for for2 for3 while while2 repeat assignment pointer pointer2 array_definition array_definition2 array char_array 

clean:
	rm bin/*

FORCE: ;
